/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketRouteImport } from './routes/ticket'
import { Route as ResolveRouteImport } from './routes/resolve'
import { Route as DemuxRouteImport } from './routes/demux'
import { Route as ClustersRouteImport } from './routes/clusters'
import { Route as BoardRouteImport } from './routes/board'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClusterIdRouteImport } from './routes/cluster.$id'

const TicketRoute = TicketRouteImport.update({
  id: '/ticket',
  path: '/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const ResolveRoute = ResolveRouteImport.update({
  id: '/resolve',
  path: '/resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const DemuxRoute = DemuxRouteImport.update({
  id: '/demux',
  path: '/demux',
  getParentRoute: () => rootRouteImport,
} as any)
const ClustersRoute = ClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClusterIdRoute = ClusterIdRouteImport.update({
  id: '/cluster/$id',
  path: '/cluster/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/clusters': typeof ClustersRoute
  '/demux': typeof DemuxRoute
  '/resolve': typeof ResolveRoute
  '/ticket': typeof TicketRoute
  '/cluster/$id': typeof ClusterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/clusters': typeof ClustersRoute
  '/demux': typeof DemuxRoute
  '/resolve': typeof ResolveRoute
  '/ticket': typeof TicketRoute
  '/cluster/$id': typeof ClusterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/clusters': typeof ClustersRoute
  '/demux': typeof DemuxRoute
  '/resolve': typeof ResolveRoute
  '/ticket': typeof TicketRoute
  '/cluster/$id': typeof ClusterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board'
    | '/clusters'
    | '/demux'
    | '/resolve'
    | '/ticket'
    | '/cluster/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/board'
    | '/clusters'
    | '/demux'
    | '/resolve'
    | '/ticket'
    | '/cluster/$id'
  id:
    | '__root__'
    | '/'
    | '/board'
    | '/clusters'
    | '/demux'
    | '/resolve'
    | '/ticket'
    | '/cluster/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRoute
  ClustersRoute: typeof ClustersRoute
  DemuxRoute: typeof DemuxRoute
  ResolveRoute: typeof ResolveRoute
  TicketRoute: typeof TicketRoute
  ClusterIdRoute: typeof ClusterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ticket': {
      id: '/ticket'
      path: '/ticket'
      fullPath: '/ticket'
      preLoaderRoute: typeof TicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resolve': {
      id: '/resolve'
      path: '/resolve'
      fullPath: '/resolve'
      preLoaderRoute: typeof ResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demux': {
      id: '/demux'
      path: '/demux'
      fullPath: '/demux'
      preLoaderRoute: typeof DemuxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clusters': {
      id: '/clusters'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof ClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cluster/$id': {
      id: '/cluster/$id'
      path: '/cluster/$id'
      fullPath: '/cluster/$id'
      preLoaderRoute: typeof ClusterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRoute,
  ClustersRoute: ClustersRoute,
  DemuxRoute: DemuxRoute,
  ResolveRoute: ResolveRoute,
  TicketRoute: TicketRoute,
  ClusterIdRoute: ClusterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
